// react-mobx-template-vite-ts/template/src/views/Login.tsx
import { Button, Form, FormProps, Input } from 'antd'
import { observer } from 'mobx-react-lite'
import { useCallback, useEffect, useState } from 'react'
import { getCaptchaApi } from '@/api/user.ts'
import { useStores } from '@/hooks/useAppStore.ts'
import './login.scss'
import { useNavigate } from 'react-router-dom'

export const Login = observer(() => {
  const {globalStore} = useStores()
  const navigate = useNavigate()
  const [captchaImg, setCaptchaImg] = useState('')
  const [loginState, setLoginState] = useState({
    username: '',
    password: '',
    captcha: ''
  })
  const getCaptcha = useCallback(async () => {
    const [, result] = await getCaptchaApi()
    if (result) {
      const imgData = new Blob([result as never], { type: 'image/svg+xml' })
      setCaptchaImg(URL.createObjectURL(imgData))
    }
  }, [])
  useEffect(() => {
    void getCaptcha()
  }, [getCaptcha])

  const login: FormProps<LoginFieldType>['onFinish'] = (values: LoginFieldType) => {
    console.log(values)
    void globalStore.getUserInfo(values).then((res) => {
      console.log('login', res)
      if (res?.token?.access_token) {
        navigate('/home')
      }
      return
    })
  }
  return (
    <div className="login-container">
      <div className="background">
        <div className="shape"></div>
        <div className="shape"></div>
      </div>
      <Form className="login-form" initialValues={loginState} onFinish={login}>
        <h3 w-full>React Admin</h3>
        <Form.Item<LoginFieldType>
          name={'username'}
          rules={[{ required: true, message: 'Please input your username!' }]}
        >
          <Input
            className={'login-input'}
            maxLength={30}
            placeholder={'username'}
            value={loginState.username}
            onChange={(e) => setLoginState({ ...loginState, username: e.target.value })}
          />
        </Form.Item>
        <Form.Item<LoginFieldType>
          name={'password'}
          rules={[{ required: true, message: 'Please input your username!' }]}
        >
          <Input.Password
            className={'login-input'}
            maxLength={20}
            placeholder={'密码'}
            value={loginState.password}
            onChange={(e) => setLoginState({ ...loginState, password: e.target.value })}
          />
        </Form.Item>
        <Form.Item<LoginFieldType>
          name={'captcha'}
          rules={[{ required: true, message: 'Please input your username!' }]}
        >
          <Input
            className={'login-input captcha-input flex-1 pr-0!'}
            maxLength={4}
            placeholder={'验证码'}
            suffix={
              <img
                src={captchaImg}
                alt="captcha img"
                bg-gray-100
                h-full
                w-140px
                onClick={getCaptcha}
              />
            }
            value={loginState.captcha}
            onChange={(e) => setLoginState({ ...loginState, captcha: e.target.value })}
          />
        </Form.Item>
        <Form.Item className={'login-input px-0!'} w-full>
          <Button className={'login-button'} type="primary" htmlType="submit" w-full>
            Login
          </Button>
        </Form.Item>
      </Form>
    </div>
  )
})

// vue-template/template/src/views/Login.vue
<template>
  <div class="login-container">
    <el-form class="login-form" ref="loginFormRef" :rules="loginRules" :model="loginForm">
      <div class="admin-logo">
        <img class="logo" src="../../assets/vue.svg" alt="logo" size-80px />
        <h1 class="name">Vue3 Admin</h1>
      </div>
      <el-form-item prop="username">
        <el-input placeholder="请输入用户名" v-model="loginState.loginForm.username">
          <template #prepend>
            <span class="svg-container">
              <svg-icon icon-name="ant-design:user-outlined"></svg-icon>
            </span>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item>
        <el-input
          type="password"
          placeholder="请输入密码"
          autocomplete="on"
          show-password
          v-model="loginState.loginForm.password"
          prop="password"
        >
          <template #prepend>
            <span class="svg-container">
              <svg-icon icon-name="ant-design:lock-outlined"></svg-icon>
            </span>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item prop="captcha">
        <el-input maxlength="4" v-model="loginState.loginForm.captcha" placeholder="请输入验证码">
          <template #prepend>
            <span class="svg-container">
              <svg-icon icon-name="ant-design:captcha-outlined"></svg-icon>
            </span>
          </template>
          <template #append>
            <img
              :src="loginState.captchaImg"
              alt=""
              @click.stop="getCaptcha"
              w-100px
              h-full
              border-none
              bg-gray-3
            />
          </template>
        </el-input>
      </el-form-item>

      <!-- 登录按钮 -->
      <el-button type="primary" @click="handleLogin" w-full mb-30px>登录</el-button>
    </el-form>
  </div>
</template>

<script lang="ts" setup>
import { useGlobalStore } from '@/stores/global'
import { FormInstance } from 'element-plus'
import { onMounted, reactive, useTemplateRef } from 'vue'
import { captchaApi } from '@/api/user'
import { useRouter } from 'vue-router'
import { useRouteQuery } from '@/hooks/useRouteQuery'

const router = useRouter()
const { redirect, otherQuery } = useRouteQuery()

const { login } = useGlobalStore()

const loginState = reactive({
  loginForm: {
    username: '',
    password: '',
    captcha: ''
  },
  captchaImg: '',
  loginRules: {
    userame: [{ required: true, trigger: 'blur', message: '请输入用户名' }],
    password: [{ required: true, trigger: 'blur', message: '请输入密码' }]
  }
})
const loginFormInstance = useTemplateRef<FormInstance>('loginFormRef')
const { loginForm, loginRules } = loginState

const handleLogin = () => {
  loginFormInstance.value?.validate(async (valid: boolean) => {
    if (valid) {
      try {
        const r = await login(loginForm)
        console.log(valid, r)
        // 解析重定向路径
        await router.push({
          path: redirect.value || '/',
          query: {
            ...otherQuery.value
          }
        })
      } catch {
        getCaptcha()
      }
    }
  })
}

const getCaptcha = () => {
  captchaApi().then((res) => {
    console.log(res)
    const b = new Blob([res as any], { type: 'image/svg+xml' })
    loginState.captchaImg = URL.createObjectURL(b)
  })
}

onMounted(() => {
  getCaptcha()
})
</script>

<style scoped lang="scss">
.login-container {
  @apply min-h-screen w-full;
  .login-form {
    @apply w-500px mx-auto py50px;
  }

  .admin-logo {
    @apply flex items-center justify-center my-20px;
  }

  :deep(.el-input-group__append) {
    @apply px-0;
  }
}
</style>
